#! /usr/bin/env bash

VERSION = $(cat package.json | grep version | head - 1 | awk - F: '{ print $2 }' | sed 's/[",]//g' | tr - d '[[:space:]]')
echo "Publish ${VERSION}"
ghr -t ${GITHUB_TOKEN} -recreate -name ${VERSION} v${VERSION} ./dist/addon-signed.xpi
