theme: minima

repository: linuxwolf/rfc-lookup
title: IETF RFC Lookup
author: Matthew A. Miller
email: linuxwolf@outer-planes.net
download_url: https://github.com/linuxwolf/rfc-lookup/releases/download/v0.1.0/addon-signed.xpi
